### PR TITLE
Useful title for AccountActivity

### PR DESCRIPTION
**Pull request by raphaelm**
Before:

After:

### CODE REVIEW

**Comment by Vavassor** [comment]
This is nice, but it needs to be tinted for its theme, because it doesn't show up under the light theme (white letters on white background). Also, it'd be good to animated it so it fades in with the bar background.

I might merge this as is and make these changes myself, but that's why I didn't merge it just yet.

**Comment by raphaelm** [comment]
I'm not sure what I'm doing wrong, but adding ``app:collapsedTitleTextAppearance="?attr/android:textColorPrimary"`` to the ``CollapsingToolbarLayout`` does not change anything for me regarding the light theme. If you have a good idea, go ahead!

**Comment by SkyzohKey** [comment]
Would it be possible to display the instance address too ? (ie. @ramy_test@instance.tld)

**Comment by raphaelm** [comment]
@SkyzohKey Sure, good idea. I'm currently not moving this forward as I'm not experienced with the theming issue, so I'd be glad about some help there.

**Comment by Vavassor** [comment]
I merged this and fixed the theming issue. It still animates the background differently than the text and icons, which I'd like to change, but I'm okay with it for the moment.

Also, @SkyzohKey it shows their instance name if they're on another instance, just not for the same instance as you.

**Comment by SkyzohKey** [comment]
Nice :)
Is a release planned soon ?

**Comment by Vavassor** [comment]
@SkyzohKey Yeah, I'm planning for Wednesday. So, day after tomorrow.

**Pull request merged**
