### PR TITLE
Add media upload progress. Closes #412

### LINKED ISSUE #412: Media uploading progress
As media uploads are quite unstable it would be nice if we could show progress when we upload media.
It is doable, but not easy.

### PR DESCRIPTION
**Pull request by charlag**
There's an upload progress shown on the media now.
Had some fun with merging with myself, I hope everything is okay (also couldn't help myself but formatted ComposeActivity).
photo_2017-10-29_00-06-23

### CODE REVIEW

**Comment by connyduck** [comment]
Really nice, this is a feature a wanted for a long time too. 
Some remarks:
- please remove the logging of the progress value, it totally spams logcat
- wouldn't a progress bar (circular or other) look better than a number?
- the percent number is really small, if you stay with numbers please make them bigger
- when the screen is rotated while the file is uploaded, the upload seems to restart? (maybe we should suppress recreation of the activity on config change `android:configChanges="orientation|screenSize|keyboardHidden"` in manifest?)
- add the license information on top of your new files please

(while playing with the uploads, I think I might have found what the problem with #174 is - we need to increase the socket timeout)

**Comment by moggers87** [comment]
If you do stick with text rather than a progress bar/graphic, what are you doing to do about contrast? It looks fine in the screenshot, but I can't imagine it works too well with a nearly white image.

**Comment by charlag** [comment]
@moggers87 I've implemented exactly the same thing at work. The image is dimmed (colorFilter).
Anyway, I'm experimenting with drawing something like a circular progress, but I struggle with drawing non-full circle. @connyduck did you ever do it? I'm thinking about saveLayer (which is expensive) or about vector drawable with trimEnd

**Comment by connyduck** [comment]
@charlag We could take a library like this https://github.com/dinuscxj/CircleProgressBar
(or you can check out how they do it)

**Comment by charlag** [comment]
@connyduck thanks for the lead. They're basically drawing full circle and then another non-full one on top of it. I cannot do it because I have to save the image below.
https://github.com/dinuscxj/CircleProgressBar/blob/master/circleprogressbar/src/main/java/com/dinuscxj/progressbar/CircleProgressBar.java#L313

**Comment by connyduck** [comment]
Ah yes I see the problem. What about overlaying a determinate ProgressBar? It won't be circular, but is that a problem?

**Comment by charlag** [comment]
@connyduck oh, it would complicate things in other places and will be less efficient. If nothing will work I will resort to separate ProgressBar but I would like to stay with one view per image if possible.

**Comment by connyduck** [comment]
Good look is worth an addidtional view imho, but you are the one implementing it, so you decide.
If you can't find an easy solution let us go with the percent for now

**Comment by charlag** [comment]
So, I've updated things:
* HttpLoggingInterceptor level is set to BASIC, upload progress logging is removed
* I've implemented kind of a circular progress bar. ```Canvas#saveLayer()``` is not the cheapest operation but I couln't find another way (and it's still cheaper than another view). Also we can customize it in any way we want.
* Please, please, don't do an ```android:configChanges```. It's very tricky to handle it correctly. I say we either adopt some library for component, which survives (which also brings separation of concerns and testability) - like ViewModel from Support LIbrary or Mosby or whatever. The point is, Activities and Fragments are huge now. I'd go with ViewModel (and Rx but LiveData will do). In case we won't use anything we can use ```FragmentActivity#onRetainCustomNonConfigurationInstance()``` or [retain a special fragment](https://developer.android.com/guide/topics/resources/runtime-changes.html) 
* Thanks for telling about license - I've completely overlooked it.

**Comment by charlag** [comment]
What about this? photo_2017-10-29_17-36-43

**Comment by connyduck** [comment]
👌

**Pull request merged**
