### PR TITLE
Translates: FR: Add new translations

### PR DESCRIPTION
**Pull request by nailyk-fr**
Done quickly in vim, some typo can remain. 
Build fine: https://releases.nailyk.fr/jenkins/job/F-Droid/job/k_tusky/106/console

### CODE REVIEW

**Comment by connyduck** [comment]
Thank you <3
Did you check if there are any mentions of "push" notifications in the translation?

**Comment by connyduck** [comment]
Yes, please remove them, it should be just "notifications" as we are not doing push anymore

**Comment by nailyk-fr** [comment]
Maybe I will make another PR. Gonna try browsing in every menu to ensure everything is fine. 

What about using [weblate](https://weblate.org/en/)? Is it difficult to setup?

**Comment by connyduck** [comment]
Feel free to change some more strings and tell me when this PR is ready for merging! 😊

Yes, we definitely need some translation service to make this stuff easier. Will set one up after Tusky 1.5.1 is released.

**Comment by nailyk-fr** [comment]
Should be good to go now. 
Had an issue with a not translated string (between your gist) so I added it.

**Pull request merged**
