### PR TITLE
Add basic lists support

### PR DESCRIPTION
**Pull request by charlag**
Bang! Lists list (no pun intended) and list timeline.
I miss Rx a lot but I am not sure that it is a good idea to pull it in yet.
I've decided to split Lists into ViewModel and View early, survives config changes without any dependencies by leveraging nonConfigurationInstance.
I also hate activities. Single Activity Applications FTW.

### CODE REVIEW

**Comment by connyduck** [comment]
Wow, cool feature!

Things I noticed:
- The activities you created have no shadow under the toolbar. Have a look at the other activities, there is `@layout/toolbar_shadow_shim` included.
- The items in `ListsActivity` should be bigger and separated with a `DividerItemDecoration`. Maybe even add a list icon for decoration like the web ui does?
- I think we can move the menu item up above muted&blocked users?

Do you plan to extend this with more features?

**Comment by charlag** [comment]
* Yes, you're right, I will add shadows
* Bigger like... bigger font? I can try adding an icon too.
* Makes sense!

**Comment by connyduck** [comment]
Yes, bigger font, `?attr/status_text_medium` should be the right size. Also, give it a selectableItemBackground for touch feedback!

**Comment by charlag** [comment]
Ah, crap, I always add it but now I've missed it! Thanks for noting, let's make this thing sexy.

About other features. I don't have any plans right now. It would be cool to check who's in the list and edit it but we have more high-priority tasks and I cannot promise anything. I would like it to be merge with the features it has now.

**Comment by connyduck** [comment]
ok, fine for me

**Comment by charlag** [comment]
I've updated it. Looks like this now.
I had to hardcore shim height in the layout, it doesn't work otherwise
screenshot_20180105-232223

**Comment by connyduck** [comment]
looks good except for the icon not having the same color as the text and it probably should not be an imageview but an CompoundDrawable on the TextView

**Comment by charlag** [comment]
Didn't ```CompoundDrawable``` bite you with compatibility things? Any advice?

**Comment by connyduck** [comment]
If you take the IconicDrawable the xml inflating wont be a problem and you can get the color with ThemeUtils.getColor in code :)

**Comment by charlag** [comment]
Fixed that too!

**Comment by connyduck** [comment]
excellent

**Pull request merged**
