### PR TITLE
Improvements for adding link info while composing toots

### PR DESCRIPTION
**Pull request by charlag**
- Now link title and picture are not automatically inserted white posting a link. User is given an option to add them. I had to make something like a Snackbar because it only appears at the bottom of the screen and it was too easy to miss and tap 'toot' instead.
- If user adds link info, progress is shown until everything is loaded or until some error occurs
- I changed progress bar to horizontal one. I think in the future we will post toots in the background so this progress bar will only be used for the link info loading.

There is also some automatic cleanup.

screenshot_20171018-201604

### CODE REVIEW

**Comment by charlag** [comment]
I've checked it and seems that there are some problems with the layout, I've probably forgot something. If someone won't fix this before me, I can fix it tomorrow.

**Comment by charlag** [comment]
I wasn't able to reproduce it, lgtm

screenshot_20171019-113715

**Comment by connyduck** [comment]
This looks good and works fine - but I am really not sure about it. It still feels really quirky and does only work with pasted links - sometimes I type links out or edit a pasted one.

I personally would prefer removing all link preview stuff from ComposeActivity and instead implement the Mastodon card endpoint on detail statuses https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-a-card-associated-with-a-status 
This way writing a toot gets less confusing and we get link previews for toots not created with Tusky.

**Comment by charlag** [comment]
@connyduck wow, I didn't know about such API! yes, let's just strip it out of good then. I wonder how many useless pictures were uploaded because of this...

**Comment by connyduck** [comment]
So I think I implemented most of the api. Have a look at this: https://github.com/Vavassor/Tusky/commit/70c1385104844f89d64919f9fbee4fd1725def46  (code needs some cleanup, but interface and functionality look good to me)
Do you want to do the part of removing link previews from ComposeActivity, @charlag?

**Comment by charlag** [comment]
I will look at it. Yeah, I can I'd you want

**Comment by connyduck** [comment]
yes please do & don't forget to remove the jsoup library

**Pull request closed without merging**
