### PR TITLE
Larger placeholder avatars

### PR DESCRIPTION
**Pull request by nevillepark**

### CODE REVIEW

**Comment by connyduck** [comment]
May I recommend providing the placeholder in different resolutions for mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi or even better as an vector drawable?

**Comment by nevillepark** [comment]
My computer is too low-powered to handle Android Studio, so I'll try using [this tool](https://inloop.github.io/svg2android/)…

**Comment by Vavassor** [comment]
I could merge this and provide the two resolutions as a mipmap set, at least. Or downscale the largest to get in-between ones?

**Comment by nevillepark** [comment]
Er, I should know how to figure this out, but what are the dimensions/resolutions you need?

**Comment by Vavassor** [comment]
It's the same as the launcher icon standard sizes so 48, 72, 96, 144, 192 (in pixels). mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi

**Comment by Vavassor** [comment]
Actually, I've changed my mind. Give me that high-res fella.

**Comment by nevillepark** [comment]
Lol i don't know how to image but tell me if this works? 
error_xxhdpi
missing_xxhdpi

**Pull request merged**
