### PR TITLE
Adding an about activity to the App

### PR DESCRIPTION
**Pull request by sbetelmal**

### CODE REVIEW

**Comment by alerque** [comment]
Great, but to meaningfully address what I brought up in #64 this needs more than the version number. The main reason I suggested this was as a place to hang useful links such as to the project page and the issue tracker.

**Comment by sbetelmal** [comment]
Happy to add that, could you prepare the links you see fit and I will add them to the activity.

**Comment by alerque** [comment]
> **Project website:**
> https://tusky.keylesspalace.com
>
> **Bug reports & feature requests:**
> https://github.com/Vavassor/Tusky/issues

Keep in mind that any strings here need to be localized so the less text the better, but pointing out these two key URLs should be worth the effort.

**Comment by sbetelmal** [comment]
@Vavassor Are you happy with @alerque suggestions? or do you want to take the about page to a different direction?

**Comment by Vavassor** [comment]
@sbetelmal Yeah, those sound like good contents. It might also be good to link to the Tusky@mastodon.social account, but it's not as vital.

**Comment by sbetelmal** [comment]
Hey guys,
let me know how you feel about this. I have tested it with Nexus 6P.
If you could let me know how to looks like on other devices.

@alerque @Vavassor

**Pull request merged**
