### PR TITLE
Add loading on login activity while fetching tokens

### PR DESCRIPTION
**Pull request by Pangoraw**
When coming from the chrome tab, the app was still showing the domain input for ~1 second before switching to the main activity. Now, the app shows a progress bar during this period.

I am not really aware of the naming convention, so don't hesitate to request some changes.

French Version

### CODE REVIEW

**Comment by connyduck** [comment]
oh very nice, that always irritated me
thank you :3

Two remarks:
- I would prefer "Connecting..." instead of "Connection..." as text 
- You probably should make the instance input visible again in all error cases so the users does not see the ProgressBar forever and can try again

**Comment by Pangoraw** [comment]
I am going to implement the following function :
```java
private void setLoading(boolean loadingState) {
   if (loadingState) {
          loading.setVisibility(View.VISIBLE);
          input.setVisibility(View.GONE);
   } else {
          loading.setVisibility(View.GONE);
          input.setVisibility(View.VISIBLE);
   }
}
```
and call `setLoading(false);` whenever an error is detected.
Does it work for you ?

Also, you're right about "Connecting..." I am going to change that.

**Comment by connyduck** [comment]
Sounds good!

**Comment by Pangoraw** [comment]
Updated !

**Pull request merged**
