### PR TITLE
Set caption for media

### PR DESCRIPTION
**Pull request by charlag**
So, to finish #411 - setting caption.
There are some debatable UI choices. I went for popup menu and dialog, I think it works well but can be prettier.
I set dialog window to ```SOFT_INPUT_ADJUST_RESIZE``` because otherwise dialog buttons may be invisible. It doesn't always work perfectly, though.
I think I've also fixed a bug with not deleting media URLs properly

### CODE REVIEW

**Comment by charlag** [comment]
Oh, crap, they're still separate commit, give me a sec, I will fix that

**Comment by connyduck** [comment]
Well, we won't find the perfect solution, it is just so difficult to fit that many controls on a small screen.
What do you think about removing the popup and putting a delete button directly in the dialog?
Also the dialog could need some padding imo.
And for it to be perfect the captions should be saved in the database (but I will merge it without that as well)

**Comment by charlag** [comment]
I can move it there if you think it will be better. As a third button?
Padding, yes, I agree

**Comment by connyduck** [comment]
I asked what users think about it on the Tusky mastodon acc: https://mastodon.social/@Tusky/99299292541755594

**Comment by connyduck** [comment]
So everybody seems to agree that click/long click is a bad idea. Lets stick with the popup. Can you add padding and resolve the merge conflict please?

**Comment by charlag** [comment]
Yeah, sure, will do tomorrow.

**Comment by charlag** [comment]
Done!

**Comment by charlag** [comment]
It would clse #411

**Pull request merged**
