### PR TITLE
Don't load public timlines when offscreen

### PR DESCRIPTION
**Pull request by charlag**
This looks hacky but it worked suprisingly well for me.
I am not sure you will agree with this, because it takes time to load but I believe that it's better than constantly fetching timelines user doesn't see.

### CODE REVIEW

**Comment by connyduck** [comment]
Yes I am really not sure. I personally like it that timelines load in the background, but I can understand that not everybody wants that. I think we need a complete rework of this together with timeline caching.

**Comment by charlag** [comment]
It's okay, I understand! But how would caching help? If would request the data from server every time the fragment is requested anyway.

**Comment by connyduck** [comment]
Well we could display cached toots in the background and start a network load once in the foreground, that would hide the network latency better I suppose. 
Is it ok if I close this PR for now?

**Comment by charlag** [comment]
I will close if, thanks for looking at it.

**Pull request closed without merging**
