### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by alerque**
I've started the process of localizing all the strings to Turkish. If anybody wants to help please let me know. Also if anybody has ideas for localizing Mastodon specific terminology or links to good discussions on other languages that would be great. For example

* What languages are importing "toot" as a noun or verb? What languages have picked a substitute for this? The literal verb would be "ötmek" in Turkish but that doesn't seem quite right. It doesn't have as light hearted a connotation an the English.

* A direct translation of "instance" as used in programming such as an instance of a class would be "oluşum", however this can also mean version or composition or any number of other things. The English is confusing enough here, I don't want the  confusion to be even worse in translation. For now I've been going with the equivalent of "server" just because it's a lot clearer what kind of value is requested, but I'm open to ideas.

* For "boost" I went with "yükseltmek" which seems to fit the meaning quite closely, but as this is a very  Mastodon specific usage it's possible importing the original English term would be less confusing in the long run.

If anybody sees activity or discussion related to localizing Mastodon itself or other clients into Turkish please cross link it here.

### CODE REVIEW

**Comment by carlosjs23** [comment]
Hello, I'm working on translating the Mastodon server into Spanish.

I preferred to use the translation of "normal" terms like Publish instead of toot, share instead of boost, server rather than instance.

The reason is what you mention, English can contribute to confusion in other languages.

So, until there are clear alternatives in the community to those words, I suggest that the translations be maintained in the way I mentioned. (Publish, share, server).

**Comment by alerque** [comment]
I finished off the Turkish translation (including new strings in the master branch since I originally branched) and hence have dropped the WIP from this PR. It should be ready to merge. I'm sure there will be things to fix and tweak, but it should be enough to get people started.

**Comment by Vavassor** [comment]
Thanks so much for the translation!

**Comment by umitkabuli** [comment]
I translate to Turkish v20.0 untranslated parts in menu Preferences submenu and approved. The app can update.

**Pull request merged**
