### PR TITLE
Save reply info in draft, refactor

### LINKED ISSUE #417: Saved toots forget to which status they reply
When saving toots, only the media urls, the content and the content warning are saved. We should also save the id of the parent toot, if there is one.
To avoid any confusion, there should be a possibility to see the parent toot in ComposeActivity.

### LINKED ISSUE #440: Drafts should be sorted with most recent first
Or user should be given an option to change ordering.

### PR DESCRIPTION
**Pull request by charlag**
This fixes #417 and closes #440 and there's also a little bit of refactoring.
I actually did much more than I should have done first. I've tried saving ```Mention```s but turns out I didn't need them for this. It would be a good idea to save the toot we're replying to but the DB is not ready yet for such thing. So I've just added some fields and that's it.
I didn't understand the visibility logic first. I hope I didn't break anything.
I've tried to remove as much as possible from ```ComposeActivity``` because it's huge.
Sorry that it's all smashed together but it's mostly related things.

### CODE REVIEW

**Comment by connyduck** [comment]
Wow thx for the work!

Unfortunately, this crashed when opening a saved status that was a reply

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                             at com.keylesspalace.tusky.ComposeActivity.onCreate(ComposeActivity.java:295)
                                                                             at android.app.Activity.performCreate(Activity.java:6975)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                             at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by charlag** [comment]
Ah, I fixed it and then rolled back. Weird thing, two branches of if are actually doing the same thing.

**Comment by charlag** [comment]
I hope it's fixed now.
I won't be surprised if there are other bugs as well, changes are pretty big and I didn't really test migrations (Room even has tools for that).

**Comment by connyduck** [comment]
Well I tested a bit.

If you try replying to a status that has been deleted, server return 404. We just show "an error occured". I think that should be improved, users will not know what to do.

but the big problem is this:

```
java.lang.IllegalStateException: Migration didn't properly handle TootEntity(com.keylesspalace.tusky.db.TootEntity).
                                                                          Expected:
                                                                         TableInfo{name='TootEntity', columns={uid=Column{name='uid', type='INTEGER', notNull=true, primaryKeyPosition=1}, contentWarning=Column{name='contentWarning', type='TEXT', notNull=false, primaryKeyPosition=0}, urls=Column{name='urls', type='TEXT', notNull=false, primaryKeyPosition=0}, visibility=Column{name='visibility', type='INTEGER', notNull=false, primaryKeyPosition=0}, inReplyToText=Column{name='inReplyToText', type='TEXT', notNull=false, primaryKeyPosition=0}, text=Column{name='text', type='TEXT', notNull=false, primaryKeyPosition=0}, inReplyToUsername=Column{name='inReplyToUsername', type='TEXT', notNull=false, primaryKeyPosition=0}, inReplyToId=Column{name='inReplyToId', type='TEXT', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
                                                                          Found:
                                                                         TableInfo{name='TootEntity', columns={uid=Column{name='uid', type='INTEGER', notNull=true, primaryKeyPosition=1}, contentWarning=Column{name='contentWarning', type='TEXT', notNull=false, primaryKeyPosition=0}, urls=Column{name='urls', type='TEXT', notNull=false, primaryKeyPosition=0}, visibility=Column{name='visibility', type='INTEGER', notNull=false, primaryKeyPosition=0}, inReplyToText=Column{name='inReplyToText', type='STRING', notNull=false, primaryKeyPosition=0}, text=Column{name='text', type='TEXT', notNull=false, primaryKeyPosition=0}, inReplyToUsername=Column{name='inReplyToUsername', type='STRING', notNull=false, primaryKeyPosition=0}, inReplyToId=Column{name='inReplyToId', type='STRING', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
                                                                             at com.keylesspalace.tusky.db.AppDatabase_Impl$1.validateMigration(AppDatabase_Impl.java:69)
                                                                             at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:75)
                                                                             at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:118)
                                                                             at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:299)
                                                                             at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
                                                                             at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
                                                                             at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
                                                                             at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
                                                                             at com.keylesspalace.tusky.db.TootDao_Impl.loadAll(TootDao_Impl.java:110)
                                                                             at com.keylesspalace.tusky.SavedTootActivity$FetchPojosTask.doInBackground(SavedTootActivity.java:171)
                                                                             at com.keylesspalace.tusky.SavedTootActivity$FetchPojosTask.doInBackground(SavedTootActivity.java:161)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

happens when you go to the saved toots activity after upgrading master to your branch.

If I read it correctly, colums have the wrong format (there seem to be "STRING" and "TEXT" column types)

**Comment by charlag** [comment]
@connyduck thanks for testing it properly! Will fix is as soon as I can.

**Comment by charlag** [comment]
If think I might make a request to check if the reply is still available but I am not sure. Should I just make a special case for 400 error with message telling that it may be related to the reply? I could show a dialog box/snackbar asking if we should delete the reply and post it like a regular status.

**Comment by connyduck** [comment]
Request to check would be great, but you still got the problem that the original toot could have been deleted between checking and sending the reply. We should check in the server code if the 404 status code reliably means that the original toot got deleted.

**Comment by charlag** [comment]
@connyduck good spot! I will make check for error code then.

**Comment by connyduck** [comment]
Sorry, I do not know Ruby well enough to verify it.

**Comment by charlag** [comment]
@connyduck excuse me?

**Comment by charlag** [comment]
I've fixed (and tested) migration and I've also added code to handle the 404 case.

**Comment by connyduck** [comment]
I am not sure 404 can only appear when parent toot is missing, but better than before 👍

**Comment by charlag** [comment]
@connyduck well, that's what that user dialog is for. We're saying "you know, sometimes it may be because of the missing toot". I'm not sure how to handle this better.

**Comment by connyduck** [comment]
Or make the combination of `inReplyToId`, `contentWarning`, `urls` and `text` unique in the db.

**Comment by charlag** [comment]
@connyduck I'm not sure if it's what you've asked for but now it will not make many separate records but will rather update existing one.

**Comment by connyduck** [comment]
Oh no thats not what i meant & I am not sure if it is that easy, but we can do without it for now.
If you undo the last commit https://github.com/Vavassor/Tusky/pull/449/commits/b2dad975eebbab60dcff1c9238530bd1dec29633 this is ready to merge for me!

**Comment by charlag** [comment]
Oh, sorry! This commits prevents creation of many drafts in the situation where one should be updated. Are you sure we don't need that? I'm not sure I understand the reasoning.

**Comment by connyduck** [comment]
Well, on Tusky 1.3, you can compose a toot, save it, edit it and save another copy. This way you can save multiple Toots without leaving ComposeActivity. Thats not possible anymore with your change. I would just prohibit saving EXACT duplicates of toots.

**Comment by charlag** [comment]
Ah, I see, you expect a different behaviour model than I do. I can check for exact same posts, no worries, but it will take some time and I think it should be in another PR. I will remove this commit then.

**Comment by charlag** [comment]
I've removed last commit and rebased it on master to fix merge conflicts.

**Pull request merged**
