### PR TITLE
#136  Share a link and extract the title, images, author's name

### PR DESCRIPTION
**Pull request by torrentcome**
+ create receiver package
+ create view package (make more sens for me to have a dedicated package to views)
+ add jsoup parser
+ implementation of feature 136

### CODE REVIEW

**Comment by Vavassor** [comment]
Sorry, I left this one too long and I couldn't manage merging it. Could you update this to master?

**Comment by torrentcome** [comment]
Hi Vavassor,
Ok for the update, but what happen with the R.raw.keystore_tusky_api ? i have update the master and i miss this resource, may have i to create it for compile or is something else ? 
Cheers

**Comment by Vavassor** [comment]
@torrentcome Oh, woops. I put that keystore in the .gitignore when I was on a test branch because I wasn't sure if it was confidential. But I forgot to add it back in later. It's just the public key of the current test server reformatted into a .bks file.

Anyhow, I added it now.

**Comment by torrentcome** [comment]
@Vavassor Done !

**Comment by Vavassor** [comment]
Alright it's in now. Thanks for your patience and work!

**Pull request merged**
